name: Some CI

on: [push, pull_request]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install local tools
        run: dotnet tool restore
      - name: Check format
        run: dotnet fantomas PlaygroundTests.fs --check
      - name: Build FSharpPlaygroundProject
        run: dotnet build ./FSharpPlaygroundProject/FSharpPlaygroundProject.fsproj -v d